/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dallowayfromadistance;

import org.jsoup.nodes.Document;

import java.util.ArrayList;

import org.jsoup.Jsoup;
import org.jsoup.select.Elements;

public class DallowaySearch {
    static Document dallowayText;
    public static void main(String[] args) {
        try {
            dallowayText = Jsoup.connect("https://www.gutenberg.org/cache/epub/71865/pg71865-images.html").get();
        } catch (Exception e) {
            System.out.println("Couldn't fetch the file!");
        }

        // load text into a String
        String text = dallowayText.text();

        // Elements paragraphs = dallowayText.select("p");
        // System.out.println(paragraphs);

        // num of names
        int dallowayCount = 0;
        int clarissaCount = 0;

        String[] stringPages = text.split("Pg\\s+\\d+");

        ArrayList<String> pages = new ArrayList<>();

        // add pages to ArrayList
        for (int i = 0; i < stringPages.length; i++) {
            pages.add(stringPages[i]);
        }

        ArrayList<String[]> fullSplitText = new ArrayList<>(); 

        // add word arrays to ArrayList
        for (int i = 0; i < pages.size(); i++) {
            fullSplitText.add(stringPages[i].split(" "));
        }

        // for (int i = 0; i < fullSplitText.size(); i++) {
        //     System.out.println(Arrays.toString(fullSplitText.get(i)));
        // }

        //iterate through string to find # of names
        for (int p = 0; p < fullSplitText.size(); p++) {
            clarissaCount = 0;
            dallowayCount = 0;

            for (int w = 0; w < fullSplitText.get(p).length; w++) {
                // how many are split on hyphens?
                if (fullSplitText.get(p)[w].contains("Clarissa")) {
                    clarissaCount++;
                } 
                if (fullSplitText.get(p)[w].contains("Dalloway")) {
                    dallowayCount++;
                }
            }
            System.out.println("Page " + (p + 3) + " Clarissa Count: " + clarissaCount);
            System.out.println("Page " + (p + 3) + " Dalloway Count: " + dallowayCount);
        }
    }
}
