/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dallowayfromadistance;

import org.jsoup.nodes.Document;
import org.jsoup.Jsoup;
import org.jsoup.select.Elements;
import java.util.*;

public class HyphenSearch {
    // TODO: DO M-DASHES TOO
    static Document dallowayText;
    public static void main(String[] args) {
        try {
            dallowayText = Jsoup.connect("https://www.gutenberg.org/cache/epub/71865/pg71865-images.html").get();
        } catch (Exception e) {
            System.out.println("Couldn't fetch the file!");
        }

        // load paragraphs only
        String text = dallowayText.text();

        Elements paragraphs = dallowayText.select("p");
        System.out.println(paragraphs);

        // num of hyphens
        int hyphenCount = 0;

        String[] stringPages = text.split("Pg\\s+\\d+");

        ArrayList<String> pages = new ArrayList<>();

        for (int i = 0; i < stringPages.length; i++) {
            pages.add(stringPages[i]);
        }

        ArrayList<String[]> fullSplitText = new ArrayList<>(); 

        for (int i = 0; i < pages.size(); i++) {
            fullSplitText.add(stringPages[i].split(" "));
        }

        // for (int i = 0; i < fullSplitText.size(); i++) {
        //     System.out.println(Arrays.toString(fullSplitText.get(i)));
        // }

        hyphenCount = 0;

        //iterate through string to find # of hyphens
        for (int p = 0; p < fullSplitText.size(); p++) {
            System.out.print("page " + (p + 3) + ": ");
            hyphenCount = 0;
            for (int w = 0; w < fullSplitText.get(p).length; w++) {
                if (fullSplitText.get(p)[w].contains("-")) {
                    hyphenCount++;
                } 
                if (fullSplitText.get(p)[w].contains("—")) {
                    hyphenCount++;
                }
            }
            System.out.println(hyphenCount);
        }
    }
}
